### PR TITLE
Hint at what to actually do

### PR DESCRIPTION
**Pull request by till**
I propose to add this as `.config/ansible-lint.yml` did not work, but an `.ansible-lint` in the root of the repository works right away.

### CODE REVIEW

**Comment by ssbarnea** [comment]
This was not working because you used an old version of the linter. The current version is able to correctly recognize the new location. Closing as no longer needed.

**Comment by till** [comment]
@ssbarnea When did you update it? I made the pr when I first used it.

**Comment by till** [comment]
#105 🙈

**Comment by ssbarnea** [comment]
Let me known if it still does not work with last version.

**Pull request closed without merging**
